### ISSUE TITLE
missing binary operator when trying to compile.

### ISSUE THREAD

**Issue by El-Virus** [madler/spoof#2]
Trying to compile either ruse or spoof produces the following error:
`error: missing binary operator before token "("`
on every line including `__has_builtin(`.
I'm unable to determine why this error is produced or how to fix it. Any ideas?
Thanks in advance.

**Comment by madler** [comment]
What compiler?

What you can do for now is to simply comment out the lines from `#if defined(__has_builtin)`... to `#else` inclusively, and the `#endif`. You clearly don't have the builtins.

**Comment by El-Virus** [comment]
Both gcc and cc. I'm on ubuntu 20.04 and it seems kali doesn't want to either.

**Comment by madler** [comment]
Should work now with gcc. See https://github.com/madler/spoof/commit/3ff7ba1565f0924317c529c1f10fefdf905ec323
